### ISSUE TITLE
Image size mismatch on AMI registration

### ISSUE THREAD

**Issue by ZackaryWelch** [cperciva/bsdec2-image-upload#9]
The EC2 API request includes a hardcoded file size:
"BlockDeviceMapping.1.Ebs.VolumeSize=10&"

I ran into an error when uploading an image whose volume size was 16GB instead of 10GB. After changing it to "16" the request succeeded. The value should correspond to the file size instead of being hardcoded.

**Comment by cperciva** [comment]
Hi @ZackaryWelch,

This is partially intentional -- if the disk image is < 10 GB, I want to tell EC2 to use a 10 GB disk because that's what I want as a default disk size for FreeBSD/EC2 instances.  But yes, I should tell it to use a larger disk if the image is bigger.

Want to provide a patch?  Should be pretty straightforward.

**Comment by ZackaryWelch** [comment]
Sure. I'll have it use the disk size rounded to the nearest GB if the size is greater than 10 and make a PR.

**Comment by cperciva** [comment]
I think you mean rounded *up* rather than to the *nearest* GB.  Thanks for taking care of this.

**Comment by cperciva** [comment]
Please try the latest tree.

**Comment by ZackaryWelch** [comment]
Awesome! Thank you very much.
